const projectData = [
  {
    name: "Offerlines",
    desc: 'An e-commerce web app built with <span class="text-warning">NextJs</span>, <span class="text-warning">Redux</span> ,<span class="text-warning">Styled Components</span>, <span class="text-warning">Material UI</span>, and  <span class="text-warning">Bootstrap</span>.',
    link: "https://offerlines.vercel.app/",
    images: [
      "../../images/offerlines/1.png",
      "../../images/offerlines/2.png",
      "../../images/offerlines/3.png",
      "../../images/offerlines/4.png",
      "../../images/offerlines/5.png",
    ],
    github: "https://github.com/jaysville/offerlines",
    id: "offerlines",
  },
  {
    name: "Electric Screen",
    desc: 'Electric screen is a movie and tv show streaming app built with <span class="text-warning">ReactJs</span>. Users can search movies , add movies to their favorites list, and view movie info. The app state was managed by <span class="text-warning">Redux Toolkit</span> and major styling done with <span class="text-warning">Styled Components</span>. ',
    link: "https://jay-electric-screens.netlify.app",
    images: [
      "../../images/electricscreen/1.png",
      "../../images/electricscreen/2.png",
      "../../images/electricscreen/3.png",
      "../../images/electricscreen/4.png",
    ],
    github: "https://github.com/jaysville/electric-sceens",
    id: "electricscreen",
  },
  {
    name: "Jay Stores",
    desc: 'Jay Stores is a minimalistic e-commerce site with pseudo-products. It was built with <span class="text-warning">ReactJs</span>.',
    link: "https://jays-stores.netlify.app/",
    images: [
      "../../images/jaystores/1.png",
      "../../images/jaystores/2.png",
      "../../images/jaystores/3.png",
      "../../images/jaystores/4.png",
      "../../images/jaystores/5.png",
    ],
    github: "https://github.com/jaysville/the-jaysville-place",
    id: "jaystores",
  },
  {
    name: "TV Wizard",
    desc: 'TvWizard is a tv show search app that lets an authenticated user to search tv shows. <br> Made with <span class="text-warning"> NodeJs</span> and <span class="text-warning"> ExpressJs.</span> I got my hands dirty working with APIs and JSON.',
    link: "https://tvwizard.herokuapp.com",
    images: [
      "../../images/tvwizard/1.png",
      "../../images/tvwizard/2.png",
      "../../images/tvwizard/3.png",
    ],
    github: "https://github.com/jaysville/tvwizard",
    id: "tvwizard",
  },
  {
    name: "Eat9ja",
    desc: 'Eat9ja is a restaurant rating app. It allows authenticated users to experience full CRUD functionality. Users can create, edit, delete and view restaurants.They can also leave reviews and star ratings on restaurants posted by other users. The restaurants are displayed on a cluster map all over Nigeria. It was made with <span class="text-warning">NodeJs</span>, <span class="text-warning">ExpressJs</span>, <span classN="text-warning">Bootstrap</span> and uses <span class="text-warning">MongoDB</span',
    link: "https://eat9ja.herokuapp.com",
    images: [
      "../../images/eat9ja/1.png",
      "../../images/eat9ja/2.png",
      "../../images/eat9ja/3.png",
      "../../images/eat9ja/4.png",
    ],
    github: "https://github.com/jaysville/eat9ja",
    id: "eat9ja",
  },
  {
    name: " Weather App",
    desc: "A mini weather app built with <span class='text-warning'>NodeJs</span>. I built this to practice working with AJAX and Web API's.",
    link: "https://jayweatherapp.herokuapp.com",
    images: [
      "../../images/weatherApp/1.png",
      "../../images/weatherApp/2.png",
      "../../images/weatherApp/3.png",
      "../../images/weatherApp/4.png",
    ],
    github: "https://github.com/jaysville/JayWeatherApp",
    id: "weatherapp",
  },
  {
    name: "Product Record Keeper",
    desc: "A minimalistic CRUD app built with <span class='text-warning'>ReactJs</span> for the client-side. It lets users upload products of 3 types which can be selected with a type switcher; Book, Furniture and DVD-disk. Users can also delete one or more products by checking their checkboxes and clicking on the mass delete button. It's backend was implemented with <span class='text-warning'>PHP</span> for the server side and <span class='text-warning'>MySQL</span> for the database.",
    link: "https://jay-scandiweb-test.netlify.app",
    images: [
      "../../images/projectrecordkeeper/1.png",
      "../../images/projectrecordkeeper/2.png",
      "../../images/projectrecordkeeper/3.png",
      "../../images/projectrecordkeeper/4.png",
      "../../images/projectrecordkeeper/5.png",
    ],
    github: "https://github.com/jaysville/scandiweb-test-final",
    id: "projectrecordkeeper",
  },
  {
    name: "Museum Of Candy",
    desc: ' A landing page for a candy museum. Made with <span class="text-warning">Bootstrap.</span>',
    link: "https://jaymuseumofcandy.netlify.app/",
    images: [
      "../../images/museumofcandy/1.png",
      "../../images/museumofcandy/2.png",
      "../../images/museumofcandy/3.png",
      "../../images/museumofcandy/4.png",
    ],
    github: "https://github.com/jaysville/JayMuseumOfCandy",
    id: "museumofcandy",
  },
];

export default projectData;
